module.exports = {
  name: 'miniCart',
  title: 'Base para carrinho flutuante - miniCart',
  description: '',
  example: '<vtex.cmc:miniCart />',
  rendered: `
<div class="portal-minicart-ref"><div class="v2-vtexsc-cart vtexsc-cart mouseActivated preLoaded" style="overflow: hidden; display: none;"><div class="vtexsc-bt"></div><div class="vtexsc-center"><div class="vtexsc-wrap "><table class="vtexsc-productList"><thead><tr><th class="cartSkuName" colspan="2">Produto</th><th class="cartSkuPrice">Preço</th><th class="cartSkuQuantity">Quantidade</th><th class="cartSkuActions">Excluir</th></tr></thead><tbody><tr><td class="cartSkuImage"><a class="sku-imagem" href="/produto-teste/p"><img height="71" width="71" alt="Produto Teste sku teste" src="https://example.vteximg.com.br/arquivos/ids/155397-79-79/desodorante-aerosol-rexona-antibacteriano---invisible-150ml_172062850_7506306244177E.jpg?v=637257028821200000"></a></td><td class="cartSkuName"><h4><a href="/produto-teste/p">Produto Teste sku teste</a></h4><p class="availability"></p></td><td class="cartSkuPrice"><div class="cartSkuUnitPrice"><span class="bestPrice">R$ 100,00</span></div></td><td class="cartSkuQuantity"><div class="cartSkuQtt"><span class="cartSkuQttTxt"><span class="vtexsc-skuQtt">1</span></span></div></td><td class="cartSkuActions"><span class="cartSkuRemove" data-index="0"><a href="javascript:void(0);" class="text" style="display: none;">excluir</a></span><div class="vtexsc-overlay" style="display: none;"></div></td></tr><tr><td class="cartSkuImage"><a class="sku-imagem" href="/produto-teste-003-copy-4-/p"><img height="71" width="71" alt="Maionese Hellmann´s Tradicional 500g" src="https://example.vteximg.com.br/arquivos/ids/155408-79-79/13740811419678.jpg?v=637263994482530000"></a></td><td class="cartSkuName"><h4><a href="/produto-teste-003-copy-4-/p">Maionese Hellmann´s Tradicional 500g</a></h4><p class="availability"></p></td><td class="cartSkuPrice"><div class="cartSkuUnitPrice"><span class="bestPrice">R$ 2,19</span></div></td><td class="cartSkuQuantity"><div class="cartSkuQtt"><span class="cartSkuQttTxt"><span class="vtexsc-skuQtt">1</span></span></div></td><td class="cartSkuActions"><span class="cartSkuRemove" data-index="1"><a href="javascript:void(0);" class="text" style="display: none;">excluir</a></span><div class="vtexsc-overlay" style="display: none;"></div></td></tr></tbody></table></div><div class="cartFooter clearfix"><div class="cartTotal">Total<span class="vtexsc-totalCart"><span class="vtexsc-text">R$ 102,19</span></span></div><a href="/checkout/#/orderform" class="cartCheckout"></a></div></div><div class="vtexsc-bb"></div></div></div>
<script>$('.portal-minicart-ref').minicart({ showMinicart: true, showTotalizers: false  , showShippingOptions: false });</script>
`,
};
